# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../playbook.yml"
  end

  config.vm.define "node2"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.box = "bento/ubuntu-20.04"

end
